- distfile: allowing to execute the remaining code of this script (instead     of the C-program) (setting NOBIN=1); BUG-fix in `usage()' ...

diff --git a/distfile b/distfile
--- a/distfile
+++ b/distfile
@@ -1,6 +1,6 @@
 #! /bin/sh
 #
-# $Id: distfile,v 1.12 2009-03-11 17:55:24 bj Exp $
+# $Id: distfile,v 1.13 2009-04-09 12:03:39 bj Exp $
 #
 # Author: Boris Jakubith
 # E-Mail: fbj@blinx.de
@@ -22,29 +22,32 @@ fi
 
 # Now try to find a local binary version of this file ...
 #
-if [ -f "$0.bin" -a -x "$0.bin" ]; then
-    # binary version of this program exists ...
-    if [ -f "$0.c" ]; then
-	# C-source of the binary program also exists ...
-	if [ "$0.c" -nt "$0.bin" ]; then
-	    # C-source is newer => re-generate binary program ...
-	    rm -f "$0.bin"; cc "$0.c" -o "$0.bin" >/dev/null 2>&1
+NOBIN=1
+if [ -n "$NOBIN" ]; then
+    if [ -f "$0.bin" -a -x "$0.bin" ]; then
+	# binary version of this program exists ...
+	if [ -f "$0.c" ]; then
+	    # C-source of the binary program also exists ...
+	    if [ "$0.c" -nt "$0.bin" ]; then
+		# C-source is newer => re-generate binary program ...
+		rm -f "$0.bin"; cc "$0.c" -o "$0.bin" >/dev/null 2>&1
+	    fi
+	else
+	    # no C-source and we can't trust a binary only, so the binary is
+	    # silently deleted ...
+	    rm -f "$0.bin"
 	fi
-    else
-	# no C-source and we can't trust a binary only, so the binary is
-	# silently deleted ...
-	rm -f "$0.bin"
+    elif [ -f "$0.c" ]; then
+	# C-source exists => generate binary program ...
+	cc "$0.c" -o "$0.bin" >/dev/null 2>&1
     fi
-elif [ -f "$0.c" ]; then
-    # C-source exists => generate binary program ...
-    cc "$0.c" -o "$0.bin" >/dev/null 2>&1
-fi
 
-# If the local binary (still) exists after all (re-)generating steps above,
-# it will be used for the further work ...
-#
-if [ -f "$0.bin" -a -x "$0.bin" ]; then
-    exec "$0.bin" ${1+"$@"}
+    # If the local binary (still) exists after all (re-)generating steps above,
+    # it will be used for the further work ...
+    #
+    if [ -f "$0.bin" -a -x "$0.bin" ]; then
+	exec "$0.bin" ${1+"$@"}
+    fi
 fi
 
 if ! [ -d admin -a -f VERSION ]; then
@@ -65,9 +68,9 @@ VERSION=`cat VERSION`
 
 usage () {
     cat <<-EOT
-	Usage: $prog [-v] bindist [-<arcmode>] install-prefix" 1>&2
-	       $prog [-v] srcdist [-<arcmode>]" 1>&2
-	       $prog
+	Usage: $PROG [-v] bindist [-<arcmode>] install-prefix" 1>&2
+	       $PROG [-v] srcdist [-<arcmode>]" 1>&2
+	       $PROG
 
 	arcmode:
 	    gz, gzip
