- distfile: completely rewritten; added checks for this program beeing     executed in the correct directory and environment ... - version: added `binary-directory', `bindir', `source-directory', `srcdir'     commands; moved the usage-output into it's own function (`usage()');     added a check for this program beeing executed in the correct directory     ...

diff --git a/distfile b/distfile
--- a/distfile
+++ b/distfile
@@ -1,6 +1,6 @@
 #! /bin/sh
 #
-# $Id: distfile,v 1.2 2006-08-16 08:18:36 bj Exp $
+# $Id: distfile,v 1.3 2007-09-20 09:04:52 bj Exp $
 #
 # Author: Boris Jakubith
 # E-Mail: bj@isv-gmbh.de
@@ -8,37 +8,121 @@
 # Licence: GPL(v2)
 
 prog="$0"
-VERSION=`cat VERSION`
+
+if ! [ -d admin -a -f VERSION ]; then
+    echo 1>&2 "${prog}: you are probably in the wrong directory"
+    exit 64
+fi
+
+if ! [ -f admin/version ]; then
+    cat 1>&2 <<-EOT
+	${prog}: are you sure you are exceuting me in the right environment?
+	EOT
+    exit 64
+fi
 
 usage () {
-    echo "Usage: $prog bindist" 1>&2
-    echo "       $prog srcdist" 1>&2
+    cat 1>&2 <<-EOT
+	Usage: $prog bindist [bz2|bzip2|gz|gzip|zip] [install-prefix]
+	       $prog srcdist [bz2|bzip2|gz|gzip|zip]
+	EOT
     exit 64
 }
 
 if [ $# -lt 1 ]; then usage; fi
 
-case $1 in
+mode="$1"; shift
+
+SFX=.tar; ARCMODE="tar cf"; COMPRESS="gzip -9f"
+if [ $# -gt 0 ]; then
+    case $1 in
+	bz2|bzip2)
+	    SFX=.tar; ARCMODE="tar cf"; COMPRESS="bzip2 -9f"; shift
+	    ;;
+	gz|gzip)
+	    SFX=.tar; ARCMODE="tar cf"; COMPRESS="gzip -9f"; shift
+	    ;;
+	zip)
+	    SFX=.zip; ARCMODE="zip -9rq"; unset COMPRESS; shift
+	    ;;
+	*)
+	    echo 1>&2 "${0##*/}: unknown archive mode '$1'."; exit 64
+	    ;;
+    esac
+fi
+
+case $mode in
     srcdist)
-	echo -n 'Creating source archive'
-	dir="cfgfile-${VERSION}"; tarfile="$dir.tar"; echo -n ' .'
-	mkdir "../$dir"; echo -n '.'
-	find . -name 'CVS' >excludes; echo excludes >>excludes; echo -n '.'
-	tar cfX - excludes . | (cd "../$dir"; tar xf -); echo -n '.'
-	(cd ..; tar cf "$tarfile" "$dir"; gzip -9f "$tarfile"); echo -n '.'
-	rm -rf excludes "../$dir"
-	echo ". (../$tarfile.gz) done."
+	vmode=source
+	DISTDIR=`admin/version source-directory`
+	amode="$ARCMODE${COMPRESS:+, }$COMPRESS"
+	echo -n "Creating source archive ($amode) "
+##	# 0. Cleaning up the source tree ...
+##	make cleanall >/dev/null 2>&1
+	# 1. Creating directory for generating the source distribution ...
+	if ! mkdir "$DISTDIR" >/dev/null 2>&1; then
+	    (echo; echo "${prog}: attempt to create '$DISTDIR' failed") 1>&2
+	    exit 1
+	fi
+	echo -n '.'
+	# 2. Copying files into the new directory ...
+	find . \( -path '*/CVS/*' -o -path '*/CVS' \) -prune -o \
+	       \( -path "./$DISTDIR/*" -o -path "./$DISTDIR" \) -prune -o \
+	       -print \
+	| cpio -pdm "$DISTDIR" >/dev/null 2>&1
+	echo -n '.'
 	;;
     bindist)
-	if [ $# -gt 1 ]; then pfx="PREFIX=$2"; fi
-	echo -n 'Creating binary archive'
-	dir="cfgfile-${VERSION}"; tarfile="$dir.bin.tar"; echo -n ' .'
-	make "DESTDIR=$dir" "$pfx" install >/dev/null 2>&1; echo -n '.'
-	(cd $dir; tar cf "../$tarfile" .); echo -n '.'
-	gzip -9f "$tarfile"; echo -n '.'
-	mv "$tarfile.gz" ..; echo -n '.'
-	rm -rf "$dir"
-	echo ". (../$tarfile.gz) done."
+	vmode=binary
+	if [ $# -gt 0 ];then PREFIX="PREFIX=$1"; shift; fi
+	DISTDIR=`admin/version binary-directory`
+	amode="$ARCMODE${COMPRESS:+, }$COMPRESS"
+	echo -n "Creating binary archive ($amode) "
+##	# 0. Generating code ...
+##	if ! make all >/dev/null 2>&1; then
+##	    (echo; echo "${prog}: code generation failed") 1>&2
+##	    exit 1
+##	fi
+	# 1. Creating directory for generating the binary distribution ...
+	if ! mkdir "$DISTDIR" >/dev/null 2>&1; then
+	    (echo; echo "${prog}: attempt to create '$DISTDIR' failed") 1>&2
+	    exit 1
+	fi
+	echo -n '.'
+	# 2. Installing binary files in the new directory ...
+	if ! make "$PREFIX" DESTDIR="`pwd`/$DISTDIR" install >/dev/null 2>&1
+	then
+	    (echo; echo "${prog}: installing binary files failed") 1>&2
+	    rm -rf "$DISTDIR"
+	    exit 1
+	fi
+	echo -n '.'
 	;;
     *)  usage ;;
 esac
+
+# 3. Generating source archive from the new directory ...
+$ARCMODE "${DISTDIR}$SFX" "$DISTDIR"
+echo -n '.'
+
+# 4. Compressing source archive ...
+if [ -n "$COMPRESS" ]; then
+    $COMPRESS "${DISTDIR}$SFX"
+fi
+echo -n '.'
+
+# 5. Removing source code directory ...
+rm -rf "$DISTDIR"
+echo -n '.'
+
+# 6. "Guessing" the name of the archive ...
+files=(`ls "${DISTDIR}$SFX"*`)
+if [ "${#files[@]}" -ne 1 ]; then
+    (echo; echo "${prog}: archive generation failed") 1>&2
+    exit 1
+fi
+archive="${files[0]}"
+
+# 7. Moving source archive out of the source tree ...
+mv "$archive" ..
+echo '. done'
