- sh-wrapper: fixed a bug in the `out>err´-redirections in two of the error     messages ... - uninstall.c: fixed bugs ...

diff --git a/sh-wrapper b/sh-wrapper
--- a/sh-wrapper
+++ b/sh-wrapper
@@ -20,13 +20,13 @@ fi
 
 if [ ! -x "$PPATH/run" -o "$PPATH/run.c" -nt "$PPATH/run" ]; then
     if ! cc "$PPATH/run.c" -o "$PPATH/run"; then
-        echo 1>&2: "${PROG}: couldn't generate 'run'!"; exit 1
+        echo 1>&2 "${PROG}: couldn't generate 'run'!"; exit 1
     fi
 fi
 if [ ! -x "$PPATH/${PROG}.bin" -o "$PPATH/${PROG}.c" -nt "$PPATH/${PROG}.bin" ]
 then
     if ! cc "$PPATH/${PROG}.c" -o "$PPATH/${PROG}.bin"; then
-        echo 1>&2: "${PROG}: couldn't generate '${PROG}.bin'!"; exit 1
+        echo 1>&2 "${PROG}: couldn't generate '${PROG}.bin'!"; exit 1
     fi
 fi
 
